on:
  pull_request:
    types: [opened, edited]

jobs:
  label_regex:
    runs-on: ubuntu-latest
    name: Add label
    steps:
      - name: "Assign label to Final Task"
        uses: Bhacaz/label-regex@v1
        with:
          field: title
          regex: '(F|f)(I|i)(N|n)(A|a)(L|l)[ -]*(T|t)(A|a)(S|s)(K|k)'
          token: "${{ secrets.GITHUB_TOKEN }}"
