on:
  pull_request:
    types: [opened, edited]

jobs:
  label_regex:
    runs-on: ubuntu-latest
    name: Add label
    steps:
      - name: "Assign label to Final Task"
        uses: Bhacaz/label-regex@v1
        with:
          field: title
          regex: '(?P<fianl_task>final[ -]*task)'
          lowercase: true
          token: "${{ secrets.GITHUB_TOKEN }}"
